name: Check Code

on:
  pull_request:
    branches:
      - master
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: adopt
          cache: 'gradle'

      - uses: actions/cache@v2
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: change permissions of gradlew
        working-directory: api
        run: chmod +x gradlew

      - name: Test
        working-directory: api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew test jacocoTestReport sonarqube --info

      - name: Build jar
        working-directory: api
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew jar

  check-format:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-java@v2
        with:
          java-version: 15
          distribution: adopt
          cache: 'gradle'

      - name: change permissions of gradlew
        working-directory: api
        run: chmod +x gradlew

      - name: Check format
        working-directory: api
        run: ./gradlew spotlessCheck
